import { defineConfig } from 'wxt';

// Apple team ID is a personal identifier (not a secret, but it links the repo to
// your Apple account), so it's read from env (.env.local) instead of committed.
// Absent -> unsigned; set it in Xcode or use adhoc signing.
try {
  process.loadEnvFile('.env.local'); // node builtin; throws if the file is absent
} catch {
  /* no .env.local (e.g. CI) — fine, team stays undefined */
}
const APPLE_TEAM_ID = process.env.APPLE_TEAM_ID;

// Config-as-code: the Safari native project (team, bundle id, category) is
// declared here and regenerated by wxt-module-safari-xcode on `wxt build -b
// safari`, so its history lives in this file, not in a committed Xcode project.
export default defineConfig({
  // safari-install must come after safari-xcode: it xcodebuilds the project
  // that safari-xcode generates.
  modules: ['@wxt-dev/auto-icons', 'wxt-module-safari-xcode', 'wxt-module-safari-install'],
  // Generate every icon size from one SVG at build time (no committed PNGs).
  autoIcons: {
    baseIconPath: 'assets/icon.svg',
    developmentIndicator: false,
  },
  manifest: {
    // Keep this equal to safariXcode.projectName: the converter names the Xcode
    // project after manifest.name, and the module looks for .output/<projectName>.
    name: 'Milheiro',
    description:
      'Diz se vale mais comprar a passagem em milhas ou em reais, comparando R$/milheiro contra o seu baseline.',
    permissions: ['storage'],
    host_permissions: ['*://*.latamairlines.com/*'],
    // inject.js runs in the page's main world via injectScript, so it must be
    // web-accessible.
    web_accessible_resources: [
      { resources: ['inject.js'], matches: ['*://*.latamairlines.com/*'] },
    ],
    browser_specific_settings: {
      gecko: { id: 'milheiro@mracos', strict_min_version: '115.0' },
    },
  },
  safariXcode: {
    projectName: 'Milheiro',
    appCategory: 'public.app-category.travel',
    bundleIdentifier: 'br.com.mracos.milheiro',
    developmentTeam: APPLE_TEAM_ID,
    projectType: 'macos',
    openProject: false, // safari-install builds + installs headlessly instead
  },
  safariInstall: {
    team: APPLE_TEAM_ID,
    // adhoc works without adding your Apple ID to Xcode (needs Safari > Develop
    // > Allow Unsigned Extensions). Switch to 'auto' once the account is set up
    // for stable signing. Override per-run with WXT_SAFARI_SIGN.
    sign: 'adhoc',
  },
});
