import { defineConfig } from 'wxt';

// Config-as-code: the Safari native project (team, bundle id, category) is
// declared here and regenerated by wxt-module-safari-xcode on `wxt build -b
// safari`, so its history lives in this file, not in a committed Xcode project.
export default defineConfig({
  modules: ['@wxt-dev/auto-icons', 'wxt-module-safari-xcode'],
  // Generate every icon size from one SVG at build time (no committed PNGs).
  autoIcons: {
    baseIconPath: 'assets/icon.svg',
    developmentIndicator: false,
  },
  manifest: {
    name: 'Milheiro — milhas ou reais?',
    description:
      'Diz se vale mais comprar a passagem em milhas ou em reais, comparando R$/milheiro contra o seu baseline.',
    permissions: ['storage'],
    host_permissions: ['*://*.latamairlines.com/*'],
    // inject.js runs in the page's main world via injectScript, so it must be
    // web-accessible.
    web_accessible_resources: [
      { resources: ['inject.js'], matches: ['*://*.latamairlines.com/*'] },
    ],
    browser_specific_settings: {
      gecko: { id: 'milheiro@mracos', strict_min_version: '115.0' },
    },
  },
  safariXcode: {
    projectName: 'Milheiro',
    appCategory: 'public.app-category.travel',
    bundleIdentifier: 'com.mracos.Milheiro',
    developmentTeam: '693Z55YX47',
  },
});
